import { supabase } from './supabase.js';
const $=id=>document.getElementById(id); let units=[],statuses=[];
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
async function guard(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='login.html';return false}const {data:a,error}=await supabase.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();if(error||!a){await supabase.auth.signOut();location.href='login.html';return false}return true}
async function load(){const [sr,ur]=await Promise.all([supabase.from('status_categories').select('*').eq('active',true).order('sort_order'),supabase.from('units').select('*').order('unit_number')]);if(sr.error)throw sr.error;if(ur.error)throw ur.error;statuses=sr.data||[];units=ur.data||[];renderUnits();renderStatuses();renderMetrics();await loadVisitors();await loadDashboardVisitors()}
function renderMetrics(){const a=statuses.find(s=>s.name.toLowerCase()==='available');$('mTotal').textContent=units.length;$('mAvailable').textContent=a?units.filter(u=>u.status_id===a.id).length:0;$('mOther').textContent=units.length-(+$('mAvailable').textContent)}
function renderUnits(){ $('unitRows').innerHTML=units.map(u=>`<tr><td>${esc(u.unit_number)}</td><td><select data-id="${u.id}" class="ustatus">${statuses.map(s=>`<option value="${s.id}" ${s.id===u.status_id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></td><td><input data-id="${u.id}" class="buyerName" value="${escAttr(u.buyer_name||'')}" placeholder="Buyer name"></td><td><input data-id="${u.id}" class="buyerNumber" value="${escAttr(u.buyer_number||'')}" placeholder="Buyer number"></td><td><button class="save small-btn" data-save="${u.id}">Save</button></td></tr>`).join('') }
$('unitRows').onclick=async e=>{const b=e.target.closest('[data-save]');if(!b)return;const id=Number(b.dataset.save),row=units.find(u=>u.id===id);const statusId=Number(document.querySelector(`.ustatus[data-id="${id}"]`).value),name=document.querySelector(`.buyerName[data-id="${id}"]`).value.trim(),num=document.querySelector(`.buyerNumber[data-id="${id}"]`).value.trim();const {error}=await supabase.from('units').update({status_id:statusId,buyer_name:name,buyer_number:num,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);Object.assign(row,{status_id:statusId,buyer_name:name,buyer_number:num});toast(`Plot ${row.unit_number} saved`);renderMetrics()}
function renderStatuses(){ $('statusList').innerHTML=statuses.map(s=>{const c=safeColor(s.color);return `<div class="status-row"><span class="swatch" style="background:${c}"></span><input class="sname" data-id="${s.id}" value="${escAttr(s.name)}"><input class="scolor" data-id="${s.id}" type="color" value="${c}" title="Choose status color"><button class="small-btn" data-edit="${s.id}">Save</button><button class="small-btn danger" data-delete="${s.id}">Delete</button></div>`}).join('') }
$('statusForm').onsubmit=async e=>{e.preventDefault();const name=$('statusName').value.trim(),color=$('statusColor').value;if(!name)return;const {error}=await supabase.from('status_categories').insert({name,color,active:true,sort_order:statuses.length});if(error)return toast(error.message);$('statusName').value='';await load();toast('Status added')}
$('statusList').oninput=e=>{const c=e.target.closest('.scolor');if(!c)return;const sw=c.closest('.status-row')?.querySelector('.swatch');if(sw)sw.style.background=safeColor(c.value)}
$('statusList').onclick=async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const id=Number(edit.dataset.edit),name=document.querySelector(`.sname[data-id="${id}"]`).value.trim(),color=document.querySelector(`.scolor[data-id="${id}"]`).value;const {error}=await supabase.from('status_categories').update({name,color}).eq('id',id);if(error)return toast(error.message);await load();toast('Status updated')}if(del){const id=Number(del.dataset.delete),s=statuses.find(x=>x.id===id);if(!s)return;if(!confirm(`Delete "${s.name}"? Any units using it will automatically become Available.`))return;const {error}=await supabase.rpc('delete_plot_status',{p_status_id:id});if(error)return toast(error.message);await load();toast('Status deleted; affected units set to Available')}}
async function fetchVisitors(limit=null){let q=supabase.from('visitors').select('*').order('created_at',{ascending:false});if(limit)q=q.limit(limit);return await q}
function visitorRow(v){return `<tr><td class="check-col"><input type="checkbox" class="visitor-check" value="${escAttr(v.id)}"></td><td>${esc(v.name)}</td><td>${esc(v.mobile||v.phone||'')}</td><td>${esc(v.email||'')}</td><td>${esc(v.city||'')}</td><td>${new Date(v.created_at).toLocaleString()}</td></tr>`}
async function loadVisitors(){const {data,error}=await fetchVisitors();if(error){$('visitorRows').innerHTML=`<tr><td colspan="6">${esc(error.message)}</td></tr>`;return}$('visitorRows').innerHTML=(data||[]).map(visitorRow).join('')||'<tr><td colspan="6">No visitors yet.</td></tr>';updateBulkState()}
async function loadDashboardVisitors(){const {data,error}=await fetchVisitors(8);if(error){$('dashboardVisitorRows').innerHTML=`<tr><td colspan="5">${esc(error.message)}</td></tr>`;return}$('dashboardVisitorRows').innerHTML=(data||[]).map(v=>`<tr><td>${esc(v.name)}</td><td>${esc(v.mobile||v.phone||'')}</td><td>${esc(v.email||'')}</td><td>${esc(v.city||'')}</td><td>${new Date(v.created_at).toLocaleString()}</td></tr>`).join('')||'<tr><td colspan="5" class="dashboard-visitors-empty">No visitors yet.</td></tr>'}
function selectedVisitorIds(){return [...document.querySelectorAll('.visitor-check:checked')].map(x=>x.value)}
function updateBulkState(){const checks=[...document.querySelectorAll('.visitor-check')],selected=checks.filter(x=>x.checked);$('deleteSelectedVisitors').disabled=selected.length===0;$('deleteSelectedVisitors').textContent=selected.length?`Delete Selected (${selected.length})`:'Delete Selected';$('selectAllVisitors').checked=checks.length>0&&selected.length===checks.length}
$('visitorRows').onchange=e=>{if(e.target.classList.contains('visitor-check'))updateBulkState()}
$('selectAllVisitors').onchange=e=>{document.querySelectorAll('.visitor-check').forEach(c=>c.checked=e.target.checked);updateBulkState()}
$('deleteSelectedVisitors').onclick=async()=>{const ids=selectedVisitorIds();if(!ids.length)return;if(!confirm(`Delete ${ids.length} selected visitor${ids.length===1?'':'s'}? This cannot be undone.`))return;const {error}=await supabase.from('visitors').delete().in('id',ids);if(error)return toast(error.message);$('selectAllVisitors').checked=false;await loadVisitors();await loadDashboardVisitors();toast(`${ids.length} visitor${ids.length===1?'':'s'} deleted`)}
$('dashboardVisitorsBtn').onclick=()=>document.querySelector('.nav button[data-page="visitors"]').click();
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(b.dataset.page).classList.add('active');if(b.dataset.page==='visitors')loadVisitors()});
$('logout').onclick=async()=>{await supabase.auth.signOut();location.href='login.html'};
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escAttr(v){return esc(v)}function safeColor(c){return /^#[0-9a-f]{6}$/i.test(c||'')?c:'#22c55e'}
(async()=>{try{if(await guard())await load()}catch(e){console.error(e);toast(e.message||'Failed to load dashboard')}})();
