-- Run this once in Supabase SQL Editor.
create table if not exists public.hold_requests (
  id bigint generated by default as identity primary key,
  unit_number text not null,
  property_name text,
  visitor_name text,
  visitor_mobile text,
  visitor_email text,
  visitor_city text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.hold_requests enable row level security;

-- Visitors can create a request from the public IPX page.
drop policy if exists "Public can submit hold requests" on public.hold_requests;
create policy "Public can submit hold requests"
on public.hold_requests for insert
to anon, authenticated
with check (status = 'pending');

-- Logged-in admin users can view requests.
drop policy if exists "Admins can view hold requests" on public.hold_requests;
create policy "Admins can view hold requests"
on public.hold_requests for select
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

-- Logged-in admin users can update request status.
drop policy if exists "Admins can update hold requests" on public.hold_requests;
create policy "Admins can update hold requests"
on public.hold_requests for update
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));
