-- Run this once in Supabase SQL Editor.
create table if not exists public.hold_requests (
  id bigint generated by default as identity primary key,
  unit_number text not null,
  property_name text,
  source_type text not null default 'single_house' check (source_type in ('single_house','4_floor')),
  plot_number text,
  floor_number text,
  visitor_name text,
  visitor_mobile text,
  visitor_email text,
  visitor_city text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.hold_requests enable row level security;

-- Visitors can create a request from the public IPX page.
drop policy if exists "Public can submit hold requests" on public.hold_requests;
create policy "Public can submit hold requests"
on public.hold_requests for insert
to anon, authenticated
with check (status = 'pending');

-- Logged-in admin users can view requests.
drop policy if exists "Admins can view hold requests" on public.hold_requests;
create policy "Admins can view hold requests"
on public.hold_requests for select
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

-- Logged-in admin users can update request status.
drop policy if exists "Admins can update hold requests" on public.hold_requests;
create policy "Admins can update hold requests"
on public.hold_requests for update
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));


-- Add floor/source tracking to an existing hold_requests table if it was created earlier.
alter table public.hold_requests add column if not exists source_type text not null default 'single_house';
alter table public.hold_requests add column if not exists plot_number text;
alter table public.hold_requests add column if not exists floor_number text;


-- Admin bulk-delete support for hold requests.
grant delete on table public.hold_requests to authenticated;
drop policy if exists "Admins can delete hold requests" on public.hold_requests;
create policy "Admins can delete hold requests"
on public.hold_requests for delete
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

-- Admin bulk-delete support for visitors.
grant delete on table public.visitors to authenticated;
drop policy if exists "Admins can delete visitors" on public.visitors;
create policy "Admins can delete visitors"
on public.visitors for delete
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));


-- =========================================================
-- 4-FLOOR APARTMENT INVENTORY
-- Plots 157-169 each have Floor 1-4.
-- =========================================================
create table if not exists public.apartment_floors (
  id bigint generated by default as identity primary key,
  plot_number text not null,
  floor_number integer not null,
  status_id bigint,
  buyer_name text,
  buyer_number text,
  updated_at timestamptz not null default now(),
  unique(plot_number, floor_number)
);

alter table public.apartment_floors enable row level security;

-- Seed all 52 apartment floors.
insert into public.apartment_floors (plot_number, floor_number)
select p::text, f
from generate_series(157,169) p
cross join generate_series(1,4) f
on conflict (plot_number, floor_number) do nothing;

-- Give logged-in admins full control.
grant select, insert, update, delete on public.apartment_floors to authenticated;

drop policy if exists "Admins can manage apartment floors" on public.apartment_floors;
create policy "Admins can manage apartment floors"
on public.apartment_floors
for all to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

-- Public pages only need to read apartment-floor status.
grant select on public.apartment_floors to anon, authenticated;

drop policy if exists "Public can view apartment floors" on public.apartment_floors;
create policy "Public can view apartment floors"
on public.apartment_floors
for select to anon, authenticated
using (true);
